const menu = [
  {
    name: "Hamburger",
    img: "burger.jfif",
    price: "$17",
    Tasty: true,
    Summer: true,
    Winter: false,
    Vegan: false,
    Appetizer: false,
    All: true,
  },
  {
    name: "Cheeseburger",
    img: "cburger.jfif",
    price: "$19",
    Tasty: true,
    Summer: true,
    Winter: false,
    Vegan: false,
    Appetizer: false,
    All: true,
  },
  {
    name: "Ceaser Salad",
    img: "cs.jfif",
    price: "$15",
    Tasty: true,
    Summer: true,
    Winter: true,
    Vegan: false,
    Appetizer: true,
    All: true,
  },
  {
    name: "Grilled Salmion",
    img: "salmon.jfif",
    price: "$25",
    Tasty: true,
    Summer: false,
    Winter: true,
    Vegan: false,
    Appetizer: false,
    All: true,
  },
  {
    name: "NY Strip Steak",
    img: "steak.jfif",
    price: "$50",
    Tasty: true,
    Summer: false,
    Winter: true,
    Vegan: false,
    Appetizer: false,
    All: true,
  },
  {
    name: "Mac and Cheese",
    img: "mc.jfif",
    price: "$12",
    Tasty: true,
    Summer: true,
    Winter: true,
    Vegan: false,
    Appetizer: true,
    All: true,
  },
  {
    name: "Calamari",
    img: "burger.jfif",
    price: "$17",
    Tasty: true,
    Summer: true,
    Winter: false,
    Vegan: false,
    Appetizer: true,
    All: true,
  },
  {
    name: "Beans",
    img: "burger.jfif",
    price: "$8",
    Tasty: false,
    Summer: true,
    Winter: true,
    Vegan: true,
    Appetizer: true,
    All: true,
  },
  {
    name: "Tuna Tartar",
    img: "bt.jfif",
    price: "$23",
    Tasty: true,
    Summer: true,
    Winter: true,
    Vegan: false,
    Appetizer: true,
    All: true,
  },
  {
    name: "French Fries",
    img: "burger.jfif",
    price: "$17",
    Tasty: true,
    Summer: true,
    Winter: false,
    Vegan: false,
    Appetizer: true,
    All: true,
  }
]