const menu = [
  {
    name: "Hamburger",
    img: "burger.jpg",
    price: "$17",
    Tasty: true,
    Summer: true,
    Winter: false,
    Vegan: false,
    Appetizer: false,
    All: true,
  },
  {
    name: "Cheeseburger",
    img: "cburger.jpg",
    price: "$19",
    Tasty: true,
    Summer: true,
    Winter: false,
    Vegan: false,
    Appetizer: false,
    All: true,
  },
  {
    name: "Ceaser Salad",
    img: "cs.jpg",
    price: "$15",
    Tasty: true,
    Summer: true,
    Winter: true,
    Vegan: false,
    Appetizer: true,
    All: true,
  },
  {
    name: "Grilled Salmion",
    img: "salmon.jpg",
    price: "$25",
    Tasty: true,
    Summer: false,
    Winter: true,
    Vegan: false,
    Appetizer: false,
    All: true,
  },
  {
    name: "NY Strip Steak",
    img: "steak.jpg",
    price: "$50",
    Tasty: true,
    Summer: false,
    Winter: true,
    Vegan: false,
    Appetizer: false,
    All: true,
  },
  {
    name: "Mac and Cheese",
    img: "mc.jpg",
    price: "$12",
    Tasty: true,
    Summer: true,
    Winter: true,
    Vegan: false,
    Appetizer: true,
    All: true,
  },
  {
    name: "Calamari",
    img: "cal.jpg",
    price: "$17",
    Tasty: true,
    Summer: true,
    Winter: false,
    Vegan: false,
    Appetizer: true,
    All: true,
  },
  {
    name: "Beans",
    img: "beans.jpg",
    price: "$8",
    Tasty: false,
    Summer: true,
    Winter: true,
    Vegan: true,
    Appetizer: true,
    All: true,
  },
  {
    name: "Tuna Tartar",
    img: "tt.jpg",
    price: "$23",
    Tasty: true,
    Summer: true,
    Winter: true,
    Vegan: false,
    Appetizer: true,
    All: true,
  },
  {
    name: "French Fries",
    img: "ff.jpg",
    price: "$17",
    Tasty: true,
    Summer: true,
    Winter: false,
    Vegan: false,
    Appetizer: true,
    All: true,
  },
  {
    name: "Brussel Sprouts",
    img: "bs.jpg",
    price: "$17",
    Tasty: true,
    Summer: false,
    Winter: true,
    Vegan: true,
    Appetizer: true,
    All: true,
  },
  {
    name: "Hot Dog",
    img: "hd.jpg",
    price: "$17",
    Tasty: true,
    Summer: true,
    Winter: true,
    Vegan: false,
    Appetizer: false,
    All: true,
  },
];

export { menu };